let products_data = [
  {
    name: "coke",
    storage: 0,
    average_stop_time: 0,
    average_purchase_time: 0,
    accum_stop_time: 0,
    sold_num: 0,
  },
  {
    name: "candy",
    storage: 90,
    average_stop_time: 4,
    average_purchase_time: 10,
    accum_stop_time: 45,
    sold_num: 5,
  },
  {
    name: "cake",
    storage: 100,
    average_stop_time: 22,
    average_purchase_time: 40,
    accum_stop_time: 77,
    sold_num: 0,
  },
  {
    name: "chocolate",
    storage: 0,
    average_stop_time: 1,
    average_purchase_time: 3,
    accum_stop_time: 30,
    sold_num: 6,
  },
  {
    name: "chips",
    storage: 55,
    average_stop_time: 18,
    average_purchase_time: 24,
    accum_stop_time: 44,
    sold_num: 16,
  },
];
